# Generated by Django 4.2.1 on 2023-05-21 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0003_alter_products_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryStore',
            fields=[
                ('contactmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.contactmodel')),
                ('products', models.ManyToManyField(to='base.products', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Фабрика',
                'verbose_name_plural': 'Фабрики',
            },
            bases=('base.contactmodel',),
        ),
    ]
